# Generated by Django 5.0.2 on 2024-02-27 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Geofence',
        ),
    ]
