# Generated by Django 5.0.2 on 2024-02-27 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_delete_geofence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='department',
        ),
    ]
