# Generated by Django 5.0.2 on 2024-02-27 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_timeslot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='start_time',
        ),
    ]
