# Generated by Django 5.0.2 on 2024-02-27 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_remove_lecture_module'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
