# Generated by Django 5.0.2 on 2024-02-27 16:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_delete_timeslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(default=django.utils.timezone.now)),
                ('end_time', models.TimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='lecture',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='qr_code',
        ),
    ]
