# Generated by Django 5.0.2 on 2024-02-28 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0019_remove_department_lecturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='location',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='time_slot',
        ),
        migrations.AddField(
            model_name='department',
            name='lecturer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='attendance.lecturer'),
        ),
    ]
