# Generated by Django 5.0.2 on 2024-02-28 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0020_remove_lecturer_latitude_remove_lecturer_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='lecturer',
        ),
    ]
