# Generated by Django 5.0.2 on 2024-02-29 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0024_department_lecturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='lecturer',
        ),
    ]
