# Generated by Django 5.0.2 on 2024-02-29 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0025_remove_department_lecturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='attendance.department'),
        ),
    ]
