# Generated by Django 5.0.2 on 2024-02-29 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0026_lecturer_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='department',
        ),
    ]
