# Generated by Django 5.0.2 on 2024-02-29 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0028_lecturer_departments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='departments',
        ),
    ]
