# Generated by Django 5.0.2 on 2024-02-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0029_remove_lecturer_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='departments',
            field=models.ManyToManyField(to='attendance.department'),
        ),
    ]
