# Generated by Django 5.0.2 on 2024-02-29 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0031_lecturer_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='semester',
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
    ]
