# Generated by Django 5.0.2 on 2024-02-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0033_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='semesters',
            field=models.ManyToManyField(to='attendance.semester'),
        ),
    ]
