# Generated by Django 5.0.2 on 2024-02-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0036_timetable_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='latitude',
            field=models.DecimalField(decimal_places=8, default=1, max_digits=9),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='longitude',
            field=models.DecimalField(decimal_places=8, default=1, max_digits=9),
        ),
    ]
