# Generated by Django 5.0.2 on 2024-02-29 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0037_alter_lecture_latitude_alter_lecture_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='latitude',
            field=models.DecimalField(decimal_places=8, default=1, max_digits=11),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='longitude',
            field=models.DecimalField(decimal_places=8, default=1, max_digits=11),
        ),
    ]
