# Generated by Django 5.0.2 on 2024-03-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0038_alter_lecture_latitude_alter_lecture_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
    ]
