# Generated by Django 5.0.2 on 2024-03-06 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0041_student_department_student_semester'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='department',
            new_name='departments',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='semester',
            new_name='semesters',
        ),
    ]
