# Generated by Django 5.0.2 on 2024-03-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0047_student_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='time_slot',
            field=models.ManyToManyField(to='attendance.timeslot'),
        ),
    ]
