# Generated by Django 5.0.2 on 2024-03-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0048_lecturer_time_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='qr_code_id',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
