# Generated by Django 5.0.2 on 2024-03-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0049_lecture_qr_code_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='qr_code_id',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
