# Generated by Django 5.0.2 on 2024-03-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0050_attendance_qr_code_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='qr_code_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
