# Generated by Django 5.0.2 on 2024-03-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0051_alter_attendance_qr_code_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
