# Generated by Django 5.0.2 on 2024-03-31 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0054_lecturer_date_of_birth_lecturer_email_lecturer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
    ]
