# Generated by Django 5.0.2 on 2024-03-31 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0056_student_first_name_student_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
