# Generated by Django 5.0.2 on 2024-04-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0057_lecturer_first_name_lecturer_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='face_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
